#! .venv/bin/python

import os
import site;
import yaml

venvSitePackage = site.getsitepackages()[0]

os.chdir(venvSitePackage)

if os.path.islink('contextLangServer') :
  print("Nothing to do...")
else :
  print("reLinking contextLangServer")
  os.system("mv contextLangServer contextLangServer-ORIG")
  os.system(
    f"ln -s ../../../../../../conTeXt-langServer/python/contextLangServer ."
  )
